server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service_platform?currentSchema=appointments
    username: customers_app
    password: customers_local
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        "[spring.json.add.type.headers]": false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    default-schema: appointments
    schemas:
      - appointments
    create-schemas: true

clients:
  customer-service:
    base-url: http://localhost:8080